drop table if exists product CASCADE;
create table product
(
    id bigint generated by default as identity,
    name varchar(255),
    image varchar(255),
    link varchar(255),
    primary key (id)
);

drop table if exists vector CASCADE;
create table vector
(
    product_id bigint,
    vector_value FLOAT,
    vector_order INT,
    constraint vector_pk primary key(product_id, vector_value, vector_order)
);
